server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/original_think_db?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update

# Application configurations (just for test purpose)
app:
  security:
    jwt:
      secret: 0A7A690F19001C887DEB108AE40C54717E740385243437A863569C91BF8AC99B
      expiration: 86400000
  token:
    default:
      verification:
        duration: 864000